Vagrant.configure("2") do |config|
  config.vm.define "maxscale1" do |maxscale1|
    maxscale1.vm.box = "ubuntu/focal64"
    maxscale1.vm.hostname = 'maxscale1'
    maxscale1.vm.box_url = "ubuntu/focal64"

    maxscale1.vm.network :private_network, ip: "192.168.56.101"
    
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("/home/vagrant/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  

    maxscale1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "maxscale1"]
    end
  end
 end
  config.vm.define "maxscale2" do |maxscale2|
    maxscale2.vm.box = "ubuntu/focal64"
    maxscale2.vm.hostname = 'maxscale2'
    maxscale2.vm.box_url = "ubuntu/focal64"

    maxscale2.vm.network :private_network, ip: "192.168.56.102"

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("/home/vagrant/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
 

    maxscale2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "maxscale2"]
    end
  end
 end
  


end


