---
- name: galera node1
  template:
    src: 50-server.cnf1.j2
    dest: /etc/mysql/conf.d/galera.cnf
    mode: 0644
  


- name: stopped mariadb
  service:
    name: mariadb
    state: stopped
  ignore_errors: yes

