---
- name: pre requirments install on ubuntu
  include: requirment.yml
  when: ansible_os_family == "Debian"
  
- name: install ubuntu mariadb
  include: mariadb.yml
  when: ansible_os_family == "Debian"

- name: node1 galera 
  include: galera1.yml
  delegate_to: db1

- name: galera_new_cluster node1
  shell: galera_new_cluster
  delegate_to: db1
  notify:
    - start mariadb node

- name: node2 galera
  include: galera2.yml
  delegate_to: db2
  notify: start mariadb node

- name: node3
  include: galera3.yml
  delegate_to: db3
  notify: start mariadb node

...