---
- name: pre requirments install on ubuntu
  include: requirment.yml
  when: ansible_os_family == "Debian"
  
- name: install maxscale mariadb
  include: maxscale.yml
  when: ansible_os_family == "Debian"

- name: Enable service maxscale
  service:
    name: maxscale
    enabled: yes
  

- name: install keepalived
  include: keepalived.yml
  when: ansible_os_family == "Debian"

- name: restart keepalived
  service:
    name: keepalived
    state: started

- name: Enable service keepalived
  service:
    name: keepalived
    enabled: yes