Vagrant.configure("2") do |config|
#   config.vm.define "proxy1" do |proxy1|
#     proxy1.vm.box = "ubuntu/focal64"
#     proxy1.vm.hostname = 'proxy1'
#     proxy1.vm.box_url = "ubuntu/focal64"

#     proxy1.vm.network :private_network, ip: "192.168.56.101"
    
#   config.vm.provision "shell" do |s|
#     ssh_pub_key = File.readlines("/home/vagrant/.ssh/id_rsa.pub").first.strip
#     s.inline = <<-SHELL
#       echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
#       echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
#     SHELL
  

#     proxy1.vm.provider :virtualbox do |v|
#       v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#       v.customize ["modifyvm", :id, "--memory", 2048]
#       v.customize ["modifyvm", :id, "--name", "proxy1"]
#     end
#   end
#  end
#   config.vm.define "proxy2" do |proxy2|
#     proxy2.vm.box = "ubuntu/focal64"
#     proxy2.vm.hostname = 'proxy2'
#     proxy2.vm.box_url = "ubuntu/focal64"

#     proxy2.vm.network :private_network, ip: "192.168.56.102"

#   config.vm.provision "shell" do |s|
#     ssh_pub_key = File.readlines("/home/vagrant/.ssh/id_rsa.pub").first.strip
#     s.inline = <<-SHELL
#       echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
#       echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
#     SHELL
 

#     proxy2.vm.provider :virtualbox do |v|
#       v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#       v.customize ["modifyvm", :id, "--memory", 2048]
#       v.customize ["modifyvm", :id, "--name", "proxy2"]
#     end
#   end
#  end
   config.vm.define "db1" do |db1|
    db1.vm.box = "ubuntu/focal64"
    db1.vm.hostname = 'db1'
    db1.vm.box_url = "ubuntu/focal64"

    db1.vm.network :private_network, ip: "192.168.56.103"

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("/home/vagrant/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  

    db1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "db1"]
    end
  end
 end

   config.vm.define "db2" do |db2|
    db2.vm.box = "ubuntu/focal64"
    db2.vm.hostname = 'db2'
    db2.vm.box_url = "ubuntu/focal64"

    db2.vm.network :private_network, ip: "192.168.56.104"

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("/home/vagrant/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
      

    db2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "db2"]
    end
  end
 end

  config.vm.define "db3" do |db3|
    db3.vm.box = "ubuntu/focal64"
    db3.vm.hostname = 'db3'
    db3.vm.box_url = "ubuntu/focal64"

    db3.vm.network :private_network, ip: "192.168.56.105"
   
    config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("/home/vagrant/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  

    db3.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "db3"]
    end
  end
 end


end


